language: rust

os:
  - linux
  - osx

dist: trusty
sudo: required

cache:
  cargo: true
  timeout: 240

before_cache:
  - rm -rf target/tmp

rust:
  - stable

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - cmake
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update       ; fi

env:
  global:
  - RUST_BACKTRACE="1"
  - RUST_FLAGS="-C debug-assertions"
  matrix:
  - TEST_DIR=core

script:
  - cargo build --release

before_deploy:
  - "echo 'make a tarball for the release binary...'"
  - ./.auto-release.sh
  - ./.github_changelog_generator.sh

deploy:
  provider: releases
  api_key:
    secure: Q0wrjfdRoieovGUe3JIcdU6iUM1kbAphVO0plvYt2aO4Y6z2TyJnfmheKBP09DhDcmVf/X6ZuRqSViaC5xuI01YF/9wwkXuXCcv2jMD8pUy4z08cVOykCe/rmlGp1oT2Ev0QCfo5klRJSFnQREUJiJpWW6/APRMSeh7uFbz9GmWF4bKObVKC+YkeGbN8rC4kPssPnZ1qt2Xbj1myDbgCH8D5yBtSlpI1hQ9iqh3Rrm2hYs6C5tKkoFxDfgGNQdgyJOfLLUCKfKHzdGL715JG+wyM/GNoH9cSug9REekIt6YCxdxanUheUA4ZJ0EZY4MSn7pL1uyJKPycWVnOqzXQM6qP4S1mNyvc6WPLe4fnSCZwGdsSZo1JT0JdomYK+bF7El+gSZoKrurBJnqixWCuU3eVu/qL31G91QSpOqi1jZTJgQwL0GKyvMpNfoEshXoGkYtEu9ByQX4TizIrIqxyKYud7URrFQAWpwDAY/bgSz5zVDkP9EEK3rEIuB/MRMeQi0zmqAEzmZ/Yus1wmHsjkc99Mlpp1ZS3VYbQO20LAsVo2kJF//TJ0aOvyaNkrERv7CL+oSlckqbjogbHlFoe3tGewvDJe0UGECT60YoeinxFGps2JmpyK6FqRXsPjLSl0gTdQp24/Sl5g1eFTpWsjEcaYXfsP6CYkdra3pHdLz4=
  file_glob: true
  file: target/release/grin*.tgz
  skip_cleanup: true
  on:
    repo: garyyu/grin
    tags: true

